# Generated by Django 5.2.10 on 2026-02-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
    ]
