# Generated by Django 5.2.10 on 2026-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_CANCEL', 'Pending Cancel Approval'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
