# Generated by Django 5.2.10 on 2026-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('can_approve_cancel', 'Can approve invoice cancellation')]},
        ),
    ]
