# Generated by Django 5.2.10 on 2026-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_invoice_approved_at_invoice_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='gst_amount',
            new_name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gst_percentage',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=12),
            preserve_default=False,
        ),
    ]
